#
# Check `contributing.md` for project build instructions.
#
# IMPORTANT: For `rabbitmq` container to work properly, you should follow the setup described in:
# https://www.rabbitmq.com/install-debian.html (inside the "With Docker" section)
#

version: '3'

services:

  site:
    image: squidfunk/mkdocs-material:4.6.3
    volumes:
      - ./hexagon_site:/docs
    ports:
      - 8000:8000

  mongodb:
    image: mongo:4.2
    ports:
      - 27017:27017

  rabbitmq:
    image: rabbitmq:3.8
    ports:
      - 5672:5672
      - 15672:15672
