
name: Pull Request

on:
  - pull_request

jobs:
  pull_request:
    name: Pull Request
    runs-on: ubuntu-latest

    steps:
      # SET UP
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Java
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Restore Cache
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: ${{ runner.os }}-gradle-

      # BUILD
      - name: Build Project
        run: ./gradlew --warn --console=plain build

      - name: Create Sample Keystores
        run: ./gradlew --warn --console=plain createCa createIdentities

      - name: Build Site
        run: ./gradlew --warn --console=plain buildSite

      - name: Test Publishing
        run: ./gradlew --warn --console=plain bintrayUpload -PbintrayDryRun=true

      - name: Upload Tests Reports (ON FAILURE)
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: test_reports
          path: "*/build/**/TEST-*.xml"
