
name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      # SET UP
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Java
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Restore Cache
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: ${{ runner.os }}-gradle-

      # BUILD
      - name: Build Project
        run: ./gradlew --warn --console=plain build

      - name: Create Sample Keystores
        run: ./gradlew --warn --console=plain createCa createIdentities

      - name: Upload Tests Reports (ON FAILURE)
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: test_reports
          path: "*/build/**/TEST-*.xml"

      # PUBLISH
      - name: Update Site
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          export REMOTE="https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git"
          git remote set-url origin "$REMOTE"
          git config --global user.email "juanjoaguililla@gmail.com"
          git config --global user.name "jaguililla"
          git clone "$REMOTE" --branch gh-pages build/gh-pages
          ./gradlew --warn --console=plain --no-daemon -x test buildSite

      - name: Publish Packages
        env:
          BINTRAY_KEY: ${{ secrets.BINTRAY_TOKEN }}
          BINTRAY_USER: jamming
        run: ./gradlew --warn --console=plain --no-daemon -x test release

      - name: Publish Site
        run: |
          cp -rf hexagon_site/build/* build/gh-pages/
          cd build/gh-pages
          git add --all
          git commit -m "Publishing to gh-pages"
          git push origin gh-pages
